# CloudFront Distribution Terraform Template
# Generated by IndraSuite for CloudFront deployment

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# Configure AWS Provider
provider "aws" {
  region     = "us-east-1" # CloudFront is global but some operations require us-east-1
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key
}

# CloudFront Distribution using the comprehensive module
module "cloudfront_distribution" {
  source = "../modules/cloudfront"

  # Basic Configuration
  distribution_name = var.distribution_name
  comment          = var.comment
  aliases          = var.aliases
  price_class      = var.price_class
  http_version     = var.http_version
  is_ipv6_enabled  = var.is_ipv6_enabled
  enabled          = var.enabled

  # Origins Configuration
  origins = var.origins

  # Cache Behaviors
  default_cache_behavior    = var.default_cache_behavior
  ordered_cache_behaviors   = var.ordered_cache_behaviors

  # Custom Error Responses
  custom_error_responses = var.custom_error_responses

  # Geographic Restrictions
  geo_restriction = var.geo_restriction

  # SSL/TLS Configuration
  viewer_certificate = var.viewer_certificate

  # Security Configuration
  viewer_protocol_policy = var.viewer_protocol_policy
  web_acl_id            = var.web_acl_id
  enable_security_headers = var.enable_security_headers
  create_security_headers_policy = var.create_security_headers_policy

  # Origin Access Control
  create_origin_access_control = var.create_origin_access_control

  # Logging Configuration
  enable_logging = var.enable_logging
  logging_config = var.logging_config

  # Security Controls
  security_controls_enabled = var.security_controls_enabled
  require_https            = var.require_https
  enable_waf              = var.enable_waf

  # CCMS Compliance Tags
  environment         = var.environment
  project_name        = var.project_name
  owner              = var.owner
  cost_center        = var.cost_center
  business_unit      = var.business_unit
  application_name   = var.application_name
  data_classification = var.data_classification

  # Additional Tags
  additional_tags = var.additional_tags
}

# Variables
variable "aws_access_key" {
  description = "AWS Access Key"
  type        = string
  sensitive   = true
}

variable "aws_secret_key" {
  description = "AWS Secret Key"
  type        = string
  sensitive   = true
}

# Basic Configuration Variables
variable "distribution_name" {
  description = "Name for the CloudFront distribution"
  type        = string
}

variable "comment" {
  description = "Comment for the CloudFront distribution"
  type        = string
  default     = ""
}

variable "aliases" {
  description = "Extra CNAMEs (alternate domain names) for this distribution"
  type        = list(string)
  default     = []
}

variable "price_class" {
  description = "Price class for the distribution"
  type        = string
  default     = "PriceClass_All"
}

variable "http_version" {
  description = "HTTP version for the distribution"
  type        = string
  default     = "http2"
}

variable "is_ipv6_enabled" {
  description = "Whether IPv6 is enabled for the distribution"
  type        = bool
  default     = true
}

variable "enabled" {
  description = "Whether the distribution is enabled"
  type        = bool
  default     = true
}

# Origins Configuration
variable "origins" {
  description = "One or more origins for this distribution"
  type = list(object({
    domain_name              = string
    origin_id                = string
    origin_path              = optional(string, "")
    connection_attempts      = optional(number, 3)
    connection_timeout       = optional(number, 10)
    use_origin_access_control = optional(bool, false)
    origin_access_control_id = optional(string, null)
    
    s3_origin_config = optional(object({
      origin_access_identity = string
    }), null)
    
    custom_origin_config = optional(object({
      http_port                = optional(number, 80)
      https_port               = optional(number, 443)
      origin_protocol_policy   = string
      origin_ssl_protocols     = optional(list(string), ["TLSv1.2"])
      origin_keepalive_timeout = optional(number, 5)
      origin_read_timeout      = optional(number, 30)
    }), null)
    
    custom_headers = optional(list(object({
      name  = string
      value = string
    })), [])
    
    origin_shield = optional(object({
      enabled              = bool
      origin_shield_region = string
    }), null)
  }))
}

# Cache Behaviors
variable "default_cache_behavior" {
  description = "Default cache behavior for this distribution"
  type = object({
    target_origin_id         = string
    allowed_methods          = optional(list(string), ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"])
    cached_methods           = optional(list(string), ["GET", "HEAD"])
    compress                 = optional(bool, true)
    field_level_encryption_id = optional(string, null)
    cache_policy_id          = optional(string, null)
    origin_request_policy_id = optional(string, null)
    response_headers_policy_id = optional(string, null)
    realtime_log_config_arn  = optional(string, null)
    trusted_key_groups       = optional(list(string), [])
    trusted_signers          = optional(list(string), [])
    
    lambda_function_associations = optional(list(object({
      event_type   = string
      lambda_arn   = string
      include_body = optional(bool, false)
    })), [])
    
    function_associations = optional(list(object({
      event_type   = string
      function_arn = string
    })), [])
    
    min_ttl     = optional(number, 0)
    default_ttl = optional(number, 86400)
    max_ttl     = optional(number, 31536000)
  })
}

variable "ordered_cache_behaviors" {
  description = "Ordered list of cache behaviors resource for this distribution"
  type = list(object({
    path_pattern             = string
    target_origin_id         = string
    viewer_protocol_policy   = string
    allowed_methods          = optional(list(string), ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"])
    cached_methods           = optional(list(string), ["GET", "HEAD"])
    compress                 = optional(bool, true)
    field_level_encryption_id = optional(string, null)
    cache_policy_id          = optional(string, null)
    origin_request_policy_id = optional(string, null)
    response_headers_policy_id = optional(string, null)
    realtime_log_config_arn  = optional(string, null)
    trusted_key_groups       = optional(list(string), [])
    trusted_signers          = optional(list(string), [])
    
    lambda_function_associations = optional(list(object({
      event_type   = string
      lambda_arn   = string
      include_body = optional(bool, false)
    })), [])
    
    function_associations = optional(list(object({
      event_type   = string
      function_arn = string
    })), [])
    
    min_ttl     = optional(number, 0)
    default_ttl = optional(number, 86400)
    max_ttl     = optional(number, 31536000)
  }))
  default = []
}

# Custom Error Responses
variable "custom_error_responses" {
  description = "One or more custom error response elements"
  type = list(object({
    error_code            = number
    response_code         = optional(number, null)
    response_page_path    = optional(string, null)
    error_caching_min_ttl = optional(number, null)
  }))
  default = []
}

# Geographic Restrictions
variable "geo_restriction" {
  description = "Geographic restriction configuration"
  type = object({
    restriction_type = string
    locations        = optional(list(string), [])
  })
  default = {
    restriction_type = "none"
    locations        = []
  }
}

# SSL/TLS Configuration
variable "viewer_certificate" {
  description = "SSL configuration for this distribution"
  type = object({
    acm_certificate_arn            = optional(string, null)
    cloudfront_default_certificate = optional(bool, true)
    iam_certificate_id             = optional(string, null)
    minimum_protocol_version       = optional(string, "TLSv1.2_2021")
    ssl_support_method             = optional(string, null)
  })
  default = {
    cloudfront_default_certificate = true
    minimum_protocol_version       = "TLSv1.2_2021"
  }
}

# Security Configuration
variable "viewer_protocol_policy" {
  description = "Use this element to specify the protocol that users can use to access the files"
  type        = string
  default     = "redirect-to-https"
}

variable "web_acl_id" {
  description = "Unique identifier that specifies the AWS WAF web ACL"
  type        = string
  default     = null
}

variable "enable_security_headers" {
  description = "Whether to enable security headers"
  type        = bool
  default     = true
}

variable "create_security_headers_policy" {
  description = "Whether to create a security headers policy"
  type        = bool
  default     = true
}

# Origin Access Control
variable "create_origin_access_control" {
  description = "Controls if CloudFront origin access control should be created"
  type        = bool
  default     = false
}

# Logging Configuration
variable "enable_logging" {
  description = "Whether to enable logging for the distribution"
  type        = bool
  default     = false
}

variable "logging_config" {
  description = "Logging configuration for the distribution"
  type = object({
    bucket          = string
    prefix          = optional(string, "")
    include_cookies = optional(bool, false)
  })
  default = {
    bucket = ""
  }
}

# Security Controls
variable "security_controls_enabled" {
  description = "Whether to enable security controls validation"
  type        = bool
  default     = true
}

variable "require_https" {
  description = "Whether to require HTTPS for all requests"
  type        = bool
  default     = true
}

variable "enable_waf" {
  description = "Whether to enable WAF protection"
  type        = bool
  default     = false
}

# CCMS Compliance Variables
variable "environment" {
  description = "Environment name (dev, staging, prod)"
  type        = string
  default     = "prod"
}

variable "project_name" {
  description = "Name of the project"
  type        = string
}

variable "owner" {
  description = "Owner of the resources"
  type        = string
  default     = "terraform-user"
}

variable "cost_center" {
  description = "Cost center for billing"
  type        = string
  default     = "engineering"
}

variable "business_unit" {
  description = "Business unit"
  type        = string
  default     = "engineering"
}

variable "application_name" {
  description = "Name of the application"
  type        = string
}

variable "data_classification" {
  description = "Data classification level"
  type        = string
  default     = "internal"
}

variable "additional_tags" {
  description = "Additional tags to apply to resources"
  type        = map(string)
  default     = {}
}

# Outputs
output "distribution_id" {
  description = "The identifier for the distribution"
  value       = module.cloudfront_distribution.distribution_id
}

output "distribution_arn" {
  description = "The ARN (Amazon Resource Name) for the distribution"
  value       = module.cloudfront_distribution.distribution_arn
}

output "distribution_domain_name" {
  description = "The domain name corresponding to the distribution"
  value       = module.cloudfront_distribution.distribution_domain_name
}

output "distribution_hosted_zone_id" {
  description = "The CloudFront Route 53 zone ID"
  value       = module.cloudfront_distribution.distribution_hosted_zone_id
}

output "distribution_status" {
  description = "The current status of the distribution"
  value       = module.cloudfront_distribution.distribution_status
}

output "distribution_urls" {
  description = "Distribution URLs and endpoints"
  value       = module.cloudfront_distribution.distribution_urls
}

output "security_controls_validation" {
  description = "Security controls validation status"
  value       = module.cloudfront_distribution.security_controls_validation
}

output "security_config" {
  description = "Summary of security configuration"
  value       = module.cloudfront_distribution.security_config
}

output "monitoring_config" {
  description = "Summary of monitoring configuration"
  value       = module.cloudfront_distribution.monitoring_config
}

output "ccms_compliance" {
  description = "CCMS compliance information"
  value       = module.cloudfront_distribution.ccms_compliance
}

output "origin_access_control_id" {
  description = "The unique identifier of the origin access control"
  value       = module.cloudfront_distribution.origin_access_control_id
}

output "tags_applied" {
  description = "All tags applied to the distribution"
  value       = module.cloudfront_distribution.tags_applied
}